# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# GitHub defaults
highlighter: pygments

# Build settings
markdown: kramdown
input: GFM

collections:
  projects:
    output: true
    permalink: /projects/:path/
  art:
    output: true
    permalink: /art/:path/
  design:
    output: true
    permalink: /design/:path/

defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      active-menu-item: "projects"
      thumbnail-size: 3
  -
    scope:
      path: ""
      type: art
    values:
      layout: photo-album
      active-menu-item: "art"
  -
    scope:
      path: ""
      type: design
    values:
      layout: null
      active-menu-item: "design"

# GitHub overrides
safe: true
lsi: false
# source: your top-level directory